addSbtPlugin("org.scalameta"             % "sbt-scalafmt"    % "2.4.3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"    % "0.1.20")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"   % "1.9.0")
addSbtPlugin("org.wartremover"           % "sbt-wartremover" % "2.4.16")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"    % "0.9.31")
