addSbtPlugin("org.scalameta"             % "sbt-scalafmt"    % "2.5.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"    % "0.4.1")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"   % "2.0.6")
addSbtPlugin("org.wartremover"           % "sbt-wartremover" % "3.0.7")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"    % "0.10.4")
