addSbtPlugin("org.scalameta"             % "sbt-scalafmt"    % "2.4.6")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"    % "0.3.1")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"   % "1.9.3")
addSbtPlugin("org.wartremover"           % "sbt-wartremover" % "3.0.3")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"    % "0.10.0")
